pkl_train_x = "./Data/x_train.pkl"
pkl_val_x = "./Data/x_val.pkl"
pkl_test_x = "./Data/x_test.pkl"
pkl_train_y = "./Data/y_train.pkl"
pkl_val_y = "./Data/y_val.pkl"
pkl_test_y = "./Data/y_test.pkl"
model_name = 'CSHierAttn'
mode_str = 'raw'
model_save_path = "./models/{}.pth".format(model_name)
s = 19
BATCH_SIZE = 16
use_dim_seq = [0, 1, 3, 4, 5]
use_dim_meta = (0, 1000)
num_app = 256
use_dim_app = list(range(num_app))
seq_len_limit = 128
flag_train = True
hidden_dim_gru = 128
hidden_dim_trans_seq = 128
hidden_dim_trans_all = 768
n_heads = 1
n_layers = 1
